import { MenuItems_MainMenu } from "src/types/types";
import { Home, BarChart, Gamepad2, Tv, Star, Calendar } from "lucide-react";

export const AUTHIMAGES = [
  "/images/auth/auth_background.jpg",
  "/images/auth/auth_background2.jpg",
  "/images/auth/auth_background3.jpg",
];

export const MAINMENU: MenuItems_MainMenu[] = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: Home, // Assign Home icon
  },
  {
    title: "Productivity",
    url: "/dashboard/productivity",
    icon: BarChart, // Assign BarChart icon
  },
  {
    title: "Gaming",
    url: "/dashboard/gaming",
    icon: Gamepad2, // Assign Gamepad2 icon
  },
  {
    title: "TV Series",
    url: "/dashboard/anime",
    icon: Tv, // Assign Tv icon
  },
];

export const ANIMEMENU: MenuItems_MainMenu[] = [
  {
    title: "Seasonal",
    url: "/dashboard/anime/seasonal",
  },
  {
    title: "Highest Rated",
    url: "/dashboard/anime/highestrated",
  },
];

export const poeMaps = [
  "Abomination Map",
  "Academy Map",
  "Acid Caverns Map",
  "Arcade Map",
  "Arena Map",
  "Arsenal Map",
  "Arid Lake Map",
  "Arachnid Nest Map",
  "Ashen Wood Map",
  "Atoll Map",
  "Basilica Map",
  "Barrows Map",
  "Belfry Map",
  "Bone Crypt Map",
  "Bog Map",
  "Bramble Valley Map",
  "Burial Chambers Map",
  "Cage Map",
  "Castle Ruins Map",
  "Canyon Map",
  "Cemetery Map",
  "Channel Map",
  "Chaos Orbs",
  "City Square Map",
  "Citadel Map",
  "Conservatory Map",
  "Courthouse Map",
  "Courtyard Map",
  "Crater Map",
  "Crimson Temple Map",
  "Crystal Ore Map",
  "Cursed Crypt Map",
  "Crimson Township Map",
  "Dungeon Map",
  "Desert Spring Map",
  "Divine Orbs",
  "Dry Sea Map",
  "Dunes Map",
  "Excavation Map",
  "Estuary Map",
  "Fields Map",
  "Flooded Mine Map",
  "Forbidden Woods Map",
  "Foundry Map",
  "Forking River Map",
  "Fungal Hollow Map",
  "Frozen Cabins Map",
  "Fortress Map",
  "Fortified Map",
  "Gardens Map",
  "Glacier Map",
  "Grave Trough Map",
  "Graveyard Map",
  "Grotto Map",
  "Iceberg Map",
  "Jungle Valley Map",
  "Lair Map",
  "Lava Chamber Map",
  "Lava Lake Map",
  "Lookout Map",
  "Maze Map",
  "Mausoleum Map",
  "Museum Map",
  "Mineral Pools Map",
  "Moon Temple Map",
  "Necropolis Map",
  "Orchard Map",
  "Overgrown Shrine Map",
  "Park Map",
  "Phantasmagoria Map",
  "Pier Map",
  "Pit Map",
  "Palace Map",
  "Port Map",
  "Plateau Map",
  "Plaza Map",
  "Prison Map",
  "Primordial Pool Map",
  "Promenade Map",
  "Ramparts Map",
  "Reef Map",
  "Residence Map",
  "Sanctuary Map",
  "Shore Map",
  "Shipyard Map",
  "Shrine Map",
  "Siege Map",
  "Silo Map",
  "Spider Forest Map",
  "Sulphur Vents Map",
  "Stagnation Map",
  "Strand Map",
  "Sunken City Map",
  "Terrace Map",
  "Thicket Map",
  "Tower Map",
  "Toxic Sewer Map",
  "Tropical Island Map",
  "Underground River Map",
  "Underground Sea Map",
  "Vaal Pyramid Map",
  "Volcano Map",
  "Wasteland Map",
  "Waste Pool Map",
  "Waterways Map",
  "Wharf Map",
  "Ziggurat Map",
] as const;
