name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install

      - name: Write Cypress environment variables to file
        run: |
          echo '{
            "CYPRESS_LOGIN_USERNAME_ADMIN": "${{ secrets.CYPRESS_LOGIN_USERNAME_ADMIN }}",
            "CYPRESS_LOGIN_PASSWORD_ADMIN": "${{ secrets.CYPRESS_LOGIN_PASSWORD_ADMIN }}"
          }' > cypress.env.json

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
          browser: chrome
          spec: |
            cypress/e2e/login.cy.ts
            cypress/e2e/loginAndVisitTVSeries.cy.ts

      - name: Upload Cypress results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-results
          path: cypress/results
